fallback = "index.html"

[[headers]]
name = "Cache-Control"
value = "public, max-age=31536000"
on = "^/assets/"

[[headers]]
name = "Content-Security-Policy"
value = "frame-ancestors https://pcarrier.com"
